services:
  keypoint_detector:
    network_mode: host
    tty: true
    build: .
    container_name: kp_container
    privileged: true
    volumes:
      - ./ros2env/src:/up/ros2env/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
      - PYTHONPATH=""
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/video6:/dev/video6
      - /dev/video7:/dev/video7
      - /dev/bus/usb:/dev/bus/usb
    entrypoint: ["/up/ros2env/entrypoint.sh"]
    command: ["bash"]
volumes:
  kp_container:

